name: Linux Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linuxBuild:
    name: "Linux build"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Install dependencies
        run: sudo apt install libatk1.0-0 librust-atk-dev libgtk-3-dev -y
      - name: Build
        run: cargo build --release --verbose
      - name: Install AppImageTool
        run: |
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          sudo mv appimagetool-x86_64.AppImage /usr/local/bin/appimagetool
          chmod +x /usr/local/bin/appimagetool
      - name: Create AppImage
        run: ./createAppImage.sh
      - uses: actions/upload-artifact@v2
        with:
          name: Kubelog-x64.AppImage
          path: Kubelog-x64.AppImage
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Kubelog-x64.AppImage
